[package]
name = "blockchain-in-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
hex-literal = "0.4.1"
serde = { version = "^1.0", features = ["derive"] }
sha3 = "0.10.8"
base16ct = { version = "0.2", features = ["alloc"] }
